FROM node:20-alpine

WORKDIR /app

ARG EMAIL_USER
ARG EMAIL_PASS
ARG PORT
ARG MONGODB_URI
ARG ADMIN_EMAIL
ARG ADMIN_PASSWORD
ARG JWT_SECRET

ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_PASS=$EMAIL_PASS
ENV PORT=$PORT
ENV MONGODB_URI=$MONGODB_URI
ENV ADMIN_EMAIL=$ADMIN_EMAIL
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD
ENV JWT_SECRET=$JWT_SECRET

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["node", "server.js"]