version: "3.8"

services:
  app:
    build: .
    container_name: email_api_app
    ports:
      - "3004:3000"
    env_file:
      - .env
    volumes:
      - ./backups:/app/backups
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: email_api_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
